### ISSUE TITLE
Specifying specific step-dependant `-R` and `-M`

### ISSUE THREAD

**Issue by benjeffery** [BEFH/snakemake-executor-plugin-lsf#10]
My specific cluster setup requires that I specify:
`-R 'select[mem>{mem_mb}] rusage[mem={mem_mb}]' -M {mem_mb}`
I couldn't see how to specify this in the config - maybe there is a way to do this? I'm currently hacking in a change to the module to achieve this.
Thanks for the plugin!

**Comment by BEFH** [comment]
Currently, the plugin only requests `rusage[mem={mem_mb}]`, with the rest being implicit. I think we can make things work with your setup, but I would like to autodetect what is needed if possible. Is there any way you could provide your `lsf.conf`?

**Comment by BEFH** [comment]
Please also include 

If you cannot provide the files, please let me know if `LSB_RESOURCE_ENFORCE` is set, and if so, what the value is. Also, `LSB_JOB_MEMLIMIT` and `LSB_MEMLIMIT_ENFORCE`. 

@dlaehnemann What do you have for `LSB_JOB_MEMLIMIT` and `LSB_MEMLIMIT_ENFORCE`?

**Comment by BEFH** [comment]
Do you specify memory limits per core or per job?

**Comment by dlaehnemann** [comment]
I have this set of parameters on my system:

```
LSB_JOB_MEMLIMIT=N
LSB_MEMLIMIT_ENFORCE=N
LSB_RESOURCE_ENFORCE="cpu memory gpu"
```

In addition, this setting might be relevant:
```
LSB_SUB_MEM_SWAP_HOST_LIMIT=Y
```

Also, @benjeffery: have you tested that each of these settings is necessary and omitting any one of them doesn't work? Maybe you could try all these different combinations and report on the exact outputs you get with some minimal working example:

* the default: `-R 'rusage[mem={mem_mb}]'`
* only `select[]` added: `-R 'select[mem>{mem_mb}] rusage[mem={mem_mb}]'`
* only `-m` added: `-R 'rusage[mem={mem_mb}]' -M {mem_mb}`
* everything: `-R 'select[mem>{mem_mb}] rusage[mem={mem_mb}]' -M {mem_mb}`

The LSF cluster configuration is far too flexible and there don't seem to be clear recommendations on how to set this up. So our cluster admin actually recommended against trying to automatically determine any memory configuration. However, I do agree that we should try to keep this plugin as general as possible, so I think all we can do is try to understand as thoroughly as possible what is going on here...

Also, to further find out what you system is configuring, you could look through your system's configuration by determining what the `$LSF_TOP` folder is and then referring to [the LSF folder structure in the docs](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=linux-example-installation-directory-structure). Important files that I have looked at so far have been:

* [`$LSF_TOP/conf/lsf.conf](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=files-lsfconf): this should contain the main configuration variables
* ['$LSF_TOP/<LSF version>/<OS type>/etc/esub`](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=controls-configuration-enable-job-submission-execution): this gets executed upon job submission, so whatever gets set there will overwrite what you might have set before

So it might also be that you simply have a very odd cluster configuration and might be easier to ask admins to reconfigure. For example the `select[mem>{mem_mb}]` setting sounds like something that should be implicitly handled when the `rusage[mem={mem_mb}]` is already set.

-----

And just document another (currently) non-workable solution: I also thought about adding something like the following to your `~/.config/snakemake/lsf_profile/config.yaml` file should work to also set your necessary extra command line arguments:
```
default-resources:
  lsf_extra: "f\"-R 'select[mem>{resources.mem_mb}]' -M {resources.mem_mb}\""
```
However, the `resources.mem_mb` specification is not currently available for the [callables in dynamic resources specification](https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#dynamic-resources), so this would require a change in snakemake itself. And I'm not sure how easy and feasible that would be.

**Comment by BEFH** [comment]
@dlaehnemann I agree with everything you said.

It should probably be fine to do `-R select[mem>{mem_mb}]` for everyone, although it may interfere with MPI jobs if the memory is per-job, and would realistically have to be the total memory for non-MPI jobs if the select matters at all. In most cases, the only reason to set this would be if your cluster allows modification of jobs after submission and you want a greater amount of memory on the execution node than the initial request for later increases, which is not something that is possible on my cluster.

I'm somewhat more concerned about setting `-M` since it sets a hard memory limit and may introduce unexpected behavior on some clusters. I think it's fine on mine, but I don't know about other clusters.

Another weird thing about @benjeffery's configuration is that `LSB_RESOURCE_ENFORCE` is set for `memory`, which means that memory should be enforced by unix cgroup, overriding `LSB_JOB_MEMLIMIT=Y` according to the documentation. I would like to know if the memory request is per-core or per-job on @benjeffery's cluster.

**Comment by lucaskbobadilla** [comment]
I am facing a similar issue. My LSF admin requires to pass both mem and scratch values with the -R parameter:

```shell
WorkflowError:
LSF job submission failed. The error message was ERROR - Specification of required resource scr (scratch) is missing or bsub syntax is incorrect.

        Minimum resource requirements are mem and scr (specified in MB)
        EXAMPLE: -R "rusage[mem=1024,scr=100]"
```

I am passing it on my LSF config profile:

```
# LSF configuration
jobs: '100'  # Maximum number of concurrent jobs
executor: lsf
cores: 60
default-resources:
  - 'lsf_project=<name>'
  - 'lsf_queue=<queue>'
  - 'lsf_jobname="snakemake_{rule}_{wildcards}"'
  - 'lsf_stdout="logs/{rule}.out"'
  - 'lsf_stderr="logs/{rule}.err"'
  - 'walltime=10000'
  - 'n=60'
  - 'mem=6000'
  - 'scr=4500'
```

But it seems that the workflow plugin is not adding the scr resource value with -R.

Any ideas how to solve this?

**Comment by dlaehnemann** [comment]
I think this issue should be easily solved within the current version of the plugin, you just need to use the (more generic) snakemake-executor-plugin-interface terms for these things and know which ones are mapped to the ones you are trying to set. These are documented here:
https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/lsf.html#advanced-resource-specifications

So for the memory, using `mem_mb` is usually the preferred, as this already makes clear the unit used. And the `scr`-definition will have to go into `lsf_extra` as this a non-standard resource. So for just these two options, a config would be:

```
default-resources:
  mem_mb: 6000
  lsf_extra: '-R "rusage[scr=100]"'
```

Does this work?

**Comment by mfansler** [comment]
I'm facing the same issue, i.e., I'm using a cluster that requires `-R 'select[mem>{mem_mb}] rusage[mem={mem_mb}]' -M {mem_mb}`.

The problem I am having is that even trying to hard code the additional two args per rule is failing due to somehow not ending up being the same number that the executor is sending in the `-R "rusage[mem={mem_mb}]"`. That is, if I put:

```python
rule foo:
  # ...
  resources:
    mem_mb=24000,
    lsf_extra='-R "select[mem>24000]" -M 24000'
```

This results in an error like:

```bash
WorkflowError:
LSF job submission failed. The error message was 
Sorry, the amount of memory selected should match the amount
of memory that your job should be reserving on the exec host
Please see:
<internal site>
for more details

i.e. selected[mem] should = rusage[mem]
Request aborted by esub. Job not submitted.
```

I've tried this both with my expected number of cores (8) and setting it to 1, just in case it is transforming.  I noted [the code for the unit conversion](https://github.com/BEFH/snakemake-executor-plugin-lsf/blob/0a20db94001974faeb76f8f8ce77f314a903f1ab/snakemake_executor_plugin_lsf/__init__.py#L153), but our system is already "LSF_UNIT_FOR_LIMITS=MB" (i.e., no multiplier).

If I omit the `mem` and `mem_mb` and try using `rusage[mem=24000]` directly, the executor still passes a default `1G`, which again leads to the same mismatch error.

Finally, I can get the executor to not pass its own memory argument by setting `mem_mb=None`. This initially seems to get the job processing further along, but ultimately the executor hits a bug:

```python
No job memory information ('mem_mb' or 'mem_mb_per_cpu') is given - submitting without. This might or might not work on your cluster.
Traceback (most recent call last):

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake/cli.py", line 2194, in args_to_api
    dag_api.execute_workflow(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        executor=args.executor,
        ^^^^^^^^^^^^^^^^^^^^^^^
    ...<46 lines>...
        scheduler_settings=scheduler_settings,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake/api.py", line 646, in execute_workflow
    workflow.execute(
    ~~~~~~~~~~~~~~~~^
        executor_plugin=executor_plugin,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        updated_files=updated_files,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake/workflow.py", line 1469, in execute
    raise e

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake/workflow.py", line 1465, in execute
    success = self.scheduler.schedule()

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake/scheduling/job_scheduler.py", line 410, in schedule
    raise e

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake/scheduling/job_scheduler.py", line 388, in schedule
    self.run(runjobs)
    ~~~~~~~~^^^^^^^^^

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake/scheduling/job_scheduler.py", line 517, in run
    executor.run_jobs(jobs)
    ~~~~~~~~~~~~~~~~~^^^^^^

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake_interface_executor_plugins/executors/base.py", line 73, in run_jobs
    self.run_job(job)
    ~~~~~~~~~~~~^^^^^

  File "envs/smk_9_16/lib/python3.13/site-packages/snakemake_executor_plugin_lsf/__init__.py", line 167, in run_job
    call += f" -R rusage[mem={mem_}]"
                              ^^^^

UnboundLocalError: cannot access local variable 'mem_' where it is not associated with a value
```

And with that I'm out of ideas.

**Comment by BEFH** [comment]
@xmao, please see this discussion. There are several issues here.

- With `-M`, memory limits are enforced by the OS instead of LSF and are therefore stricter and less tolerant of memory spikes.
- `select[mem>{mem_mb}]` requires configuration by HPC admins and may cause various failures if not configured.
   - If not configured in `lsf.shared`, it could cause either silent or other errors
   - this can refer to physical memory only, which could be problematic if swapping is OK

We may be able to examine `lsf.shared` or query `lsinfo -r` to look for configuration required for `select[mem>{mem_mb}]`, and I can be swayed on `-M`.

For `select`, the following could be put into the `get_lsf_config()` method:

```python
lsf_config["USE_SELECT"] = False
lsinfo = subprocess.run(["lsinfo", "-rw", "mem"], capture_output=True, text=True)
mem_defined = "mem: Resource name not found" not in lsinfo.stdout
if mem_defined:
    lsload = subprocess.run(["lsload", "-l"], capture_output=True, text=True)
    lsload_lines = lsload.stdout.split("\n")
    headers = lsload_lines[0].split()
    mem_col = headers.index("mem") if "mem" in headers else None
    if mem_col is not None and len(lsload_lines) > 1:
        values = [l.split()[mem_col] for l in lsload_lines[1:] if l.split() and len(l.split()) > mem_col]
        lsf_config["USE_SELECT"] = any(v != "-" for v in values)
```

For `-M`, a possibility is the following:

```
bparams = subprocess.run(["bparams", "-a"], capture_output=True, text=True)
lsf_config["USE_DASHM"] = any(
    "MEMLIMIT" in line and "= N" not in line
    for line in bparams.stdout.splitlines()
)
```

I would like to see some testing before merging it though. Do you have any thoughts, @benjeffery, @dlaehnemann?
